# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Xcode8_TabBarController' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Xcode8_TabBarController
  pod 'RAMAnimatedTabBarController', "~> 2.0.2" 
end
