# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'V2ex-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for V2ex-Swift
  pod ‘Alamofire’
  pod ‘SVProgressHUD’
  pod ‘ObjectMapper’

  target 'V2ex-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
