# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoa&&MVVM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveCocoa&&MVVM
  pod 'ReactiveCocoa', '~> 2.5’
  target 'ReactiveCocoa&&MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
