source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'KSJSONHelp'
pod 'EasyAnimation'
pod 'RAMAnimatedTabBarController', '~> 1.1.1'
pod 'Material', '~> 1.0'
pod 'TKSubmitTransition'
pod 'IQKeyboardManagerSwift'
pod 'IBAnimatable', '~> 1.2'

