# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UITableView-FDTemplateLayoutCell框架使用' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITableView-FDTemplateLayoutCell框架使用
pod 'DGTemplateLayoutCell'
end
