# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'Alamofire'


  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
